name: knowledge_app
description: A new Flutter project for organizing knowledge.
# ... other standard pubspec entries ...

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjust SDK constraints as needed

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  desktop_drop: ^0.4.4   # For desktop drag and drop
  cross_file: ^0.3.3+8    # Platform-agnostic file representation (used by desktop_drop)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  # ... assets, fonts etc. ...

    